[package]
name = "accountant"
version = "0.1.0"
authors = ["Jahfer Husain <jahferh@gmail.com>"]

[dependencies]
num = "0.1"
csv = "^0.14"
rustc-serialize = "0.3"
chrono = { version = "0.2", features = ["rustc-serialize"] }
regex = "0.1"
lazy_static = "0.2"
